apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-learning-projects
spec:
  replicas: 1
  selector:
    matchLabels:
      app: react-learning-projects
  template:
    metadata:
      labels:
        app: react-learning-projects
    spec:
      containers:
      - name: react-learning-projects
        image: mjkazin/react-learning-projects:latest
        ports:
        - containerPort: 3000
        env:
        - name: NODE_ENV
          value: "production"
        - name: REACT_APP_LOGROCKET_ID
          valueFrom:
            secretKeyRef:
              name: logrocket-id
              key: REACT_APP_LOGROCKET_ID

---
apiVersion: v1
kind: Service
metadata:
  name: react-learning-projects
spec:
  selector:
    app: react-learning-projects
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer
---
apiVersion: v1
kind: Secret
metadata:
  name: logrocket-id
type: Opaque
data:
  REACT_APP_LOGROCKET_ID: ${{ secrets.REACT_APP_LOGROCKET_ID }}
